# Generated by Django 5.1.2 on 2024-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_points', models.JSONField()),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField()),
                ('duration', models.FloatField()),
                ('vibration_level', models.CharField(choices=[('V1', 'Vibration Level 1'), ('V2', 'Vibration Level 2'), ('V3', 'Vibration Level 3')], max_length=2)),
            ],
        ),
    ]
