# Generated by Django 5.1.2 on 2024-10-25 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_points', models.JSONField()),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField()),
                ('duration', models.FloatField()),
                ('vibration_level', models.CharField(choices=[('V1', 'Level 1'), ('V2', 'Level 2')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_points', models.JSONField()),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField()),
                ('duration', models.FloatField()),
                ('vibration_level', models.CharField(choices=[('V1', 'Level 1'), ('V2', 'Level 2')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_points', models.JSONField()),
                ('frequency', models.FloatField()),
                ('intensity', models.FloatField()),
                ('duration', models.FloatField()),
                ('vibration_level', models.CharField(choices=[('V1', 'Vibration Level 1'), ('V2', 'Vibration Level 2'), ('V3', 'Vibration Level 3')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.simulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SimulationReport',
        ),
        migrations.AddField(
            model_name='control',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.simulation'),
        ),
    ]
