# Generated by Django 5.1.2 on 2024-10-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_control_sensor_simulation_simulationresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.AddField(
            model_name='sensor',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.simulation'),
            preserve_default=False,
        ),
    ]
